### ISSUE TITLE
Generate a board

### ISSUE THREAD

**Issue by Drucephus** [ajithvemasani/gamma#7]
Make valid boards at varying levels of difficulty

**Comment by Drucephus** [comment]
Investigate PySudoku for library of game generators

**Comment by ajithvemasani** [comment]
'''mermaid
classDiagram
    Sudoku <|-- EasyPuzzle
    Sudoku <|-- MediumPuzzle
    Sudoku <|-- ExpertPuzzle
    Sudoku : +bool have_puzzle
    Sudoku : +String difficuly_level
    Sudoku : +input_puzzle()
    Sudoku : +validate_puzzle()
    Sudoku : +generate_puzzle()
    
    class EasyPuzzle{
        
    }
'''

**Comment by ajithvemasani** [comment]
![Image](https://github.com/ajithvemasani/gamma/assets/170479201/94058611-d155-41cd-830a-7546da697e71)

**Comment by ajithvemasani** [comment]
"DONE" is when a new sudoku game board is generated based on user input for difficulty level.

**Comment by ajithvemasani** [comment]
```mermaid
flowchart TD
    A[Sudoku] -->  B{have a puzzle?}
    B -->|Yes| D[Input puzzle]
    B -->|No| E{difficulty level?}
    E -->|Beginner| G[Generate Easy puzzle]
    E -->|Intermediate| H[Generate Medium puzzle]
    E -->|Expert| I[Generate Expert puzzle]
```
